export declare function isLocalhostURL(str: string): boolean;
export declare function isURL(str?: string | null): boolean;
export declare const hasProtocol: (url: string) => boolean;
export declare const validateAndModifyUrl: (url: string) => string | null;
export declare const removeHttp: (url: string) => string;
export declare const urlEquals: (url?: string | null, anotherUrl?: string | null, ignoreProtocol?: boolean) => boolean;
export declare const hasSameHost: (url: string, newUrl: string) => boolean;
export declare const isSearchTerm: (url: string) => boolean;
export type SpotlightItemType = "search" | "navigation";
export declare const getUrlType: (input: string) => SpotlightItemType;
export declare const formatUrl: (url: string) => string;
